package org.specialtripsagency

import org.specialtripsagency.BookingObject
import org.specialtripsagency.Applicant
import org.specialtripsagency.Flight

rule "CalculateTotalPriceBasedOnDiscountProvided"
	
	ruleflow-group "total"
	salience -10
	no-loop true

	when
		tempApplicantObj: Applicant(numberOfTravelers > 0)
		flight: Flight(ratePerPerson > 0)
		bookingObject: BookingObject(applicant==tempApplicantObj, availableFlights==flight)
	then
		System.out.println("Running CalculateTotalPriceBasedOnDiscountProvided Rule... Calculating discount");
                System.out.println("bookingObject.getTotalPrice() value is: " + bookingObject.getTotalPrice());
		modify(bookingObject) {setTotalPrice(
				bookingObject.getTotalPrice() +
				(flight.getRatePerPerson() - flight.getPriceDiscount()) * tempApplicantObj.getNumberOfTravelers())};
		System.out.println("Calculated Total Price is: [" + bookingObject.getTotalPrice() + "]");
end
		
	