package org.specialtripsagency

import org.specialtripsagency.BookingObject
import org.specialtripsagency.Applicant
import org.specialtripsagency.Flight

rule "CalculateTotalPriceBasedOnDiscountProvided"
	
	salience -10

	when
		tempApplicantObj: Applicant(numberOfTravelers > 0)
		flight: Flight(ratePerPerson > 0 && priceDiscount > 0)
		bookingObject: BookingObject(applicant==tempApplicantObj, availableFlights==flight)
	then
		System.out.println("Running CalculateTotalPriceBasedOnDiscountProvided Rule... Calculating discount");
		modify(bookingObject) {setTotalPrice(
				bookingObject.getTotalPrice() +
				(flight.getRatePerPerson() - flight.getPriceDiscount()) * tempApplicantObj.getNumberOfTravelers())};
end
		
	