//created on: Jun 11, 2014
package org.specialtripsagency

//list any import classes here.
import org.specialtripsagency.BookingObject
import org.specialtripsagency.Applicant
import org.specialtripsagency.Flight


//declare any global variables here


rule "TotalTravelersPriceCheck"

    when
        //conditions
        applicant : Applicant(numberOfTravelers > 1)
        flight : Flight(ratePerPerson >  0)
        bookingObject : BookingObject(totalPrice == 0)
    then
        //actions
        modify(bookingObject) {setTotalPrice(flight.getRatePerPerson())};
        System.out.println("Running TotalTravelers Rule...");
        System.out.println("\t\t ratePerPerson= "+ flight.getRatePerPerson());
        System.out.println("\t\t Total price in bookingObject is ["+ bookingObject.getTotalPrice() + "]");
end