package org.specialtripsagency.dataobject;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(1064469782829be8cfeb74525b2f77b7)
 */
@org.kie.api.definition.type.Label(value = "BookingObject")
public class BookingObject  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Additional Price Discount Provided On Package")
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.Integer additionalPriceDiscount;
    
    @org.kie.api.definition.type.Label(value = "Applicant")
    @org.kie.api.definition.type.Position(value = 0)
    private org.specialtripsagency.dataobject.Applicant applicant;
    
    @org.kie.api.definition.type.Label(value = "Available Flight")
    @org.kie.api.definition.type.Position(value = 2)
    private org.specialtripsagency.dataobject.Flight availableFlights;
    
    @org.kie.api.definition.type.Label(value = "Available Hotel")
    @org.kie.api.definition.type.Position(value = 3)
    private org.specialtripsagency.dataobject.Hotel availableHotels;
    
    @org.kie.api.definition.type.Label(value = "Booking Reference Number/Identifier")
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.Integer bookingId;
    
    @org.kie.api.definition.type.Label(value = "Total Package Price")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.Integer totalPrice;
    
    @org.kie.api.definition.type.Label(value = "TravelDetails")
    @org.kie.api.definition.type.Position(value = 1)
    private org.specialtripsagency.dataobject.TravelDetails travelDetails;

    public BookingObject() {
    }

    public BookingObject(org.specialtripsagency.dataobject.Applicant applicant, org.specialtripsagency.dataobject.TravelDetails travelDetails, org.specialtripsagency.dataobject.Flight availableFlights, org.specialtripsagency.dataobject.Hotel availableHotels, java.lang.Integer totalPrice, java.lang.Integer additionalPriceDiscount, java.lang.Integer bookingId) {
        this.applicant = applicant;
        this.travelDetails = travelDetails;
        this.availableFlights = availableFlights;
        this.availableHotels = availableHotels;
        this.totalPrice = totalPrice;
        this.additionalPriceDiscount = additionalPriceDiscount;
        this.bookingId = bookingId;
    }


    
    public java.lang.Integer getAdditionalPriceDiscount() {
        return this.additionalPriceDiscount;
    }

    public void setAdditionalPriceDiscount(java.lang.Integer additionalPriceDiscount) {
        this.additionalPriceDiscount = additionalPriceDiscount;
    }
    
    public org.specialtripsagency.dataobject.Applicant getApplicant() {
        return this.applicant;
    }

    public void setApplicant(org.specialtripsagency.dataobject.Applicant applicant) {
        this.applicant = applicant;
    }
    
    public org.specialtripsagency.dataobject.Flight getAvailableFlights() {
        return this.availableFlights;
    }

    public void setAvailableFlights(org.specialtripsagency.dataobject.Flight availableFlights) {
        this.availableFlights = availableFlights;
    }
    
    public org.specialtripsagency.dataobject.Hotel getAvailableHotels() {
        return this.availableHotels;
    }

    public void setAvailableHotels(org.specialtripsagency.dataobject.Hotel availableHotels) {
        this.availableHotels = availableHotels;
    }
    
    public java.lang.Integer getBookingId() {
        return this.bookingId;
    }

    public void setBookingId(java.lang.Integer bookingId) {
        this.bookingId = bookingId;
    }
    
    public java.lang.Integer getTotalPrice() {
        return this.totalPrice;
    }

    public void setTotalPrice(java.lang.Integer totalPrice) {
        this.totalPrice = totalPrice;
    }
    
    public org.specialtripsagency.dataobject.TravelDetails getTravelDetails() {
        return this.travelDetails;
    }

    public void setTravelDetails(org.specialtripsagency.dataobject.TravelDetails travelDetails) {
        this.travelDetails = travelDetails;
    }
}