package org.specialtripsagency.dataobject;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(e18b9bbcfb8be4e5217dfe85a4b57c68)
 */
@org.kie.api.definition.type.Label(value = "Rejection")
public class Rejection  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Reason")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String reason;

    public Rejection() {
    }

    public Rejection(java.lang.String reason) {
        this.reason = reason;
    }


    
    public java.lang.String getReason() {
        return this.reason;
    }

    public void setReason(java.lang.String reason) {
        this.reason = reason;
    }
}